#!/bin/bash
#
# Cain Susko -- 2023.03.13
#
# This script takes as input the name of a directory for a coverletter and
# compiles the markdown to pdf using pandoc and latex.
#
# It requires the lualatex engine to work properly
#
# usage:
#        ./compile dirName

name=$1

input="$name/template_title.md $name/template_body.md $name/template_end.md"
outputPath="$name/$name.pdf"

pandoc $input -o $outputPath --pdf-engine lualatex
